name: 'cloudflare-pr-previews'
description: 'An action used for securely deploying cloudflare PR previews to CF Pages'
inputs:
  gh_app_key:
    required: true
  gh_app_name:
    required: true
  project_name:
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload previews
      uses: 'docker://ghcr.io/matyrobbrt/cloudflare-pr-previews:1.0.17'
      with:
        gh_app_key: ${{ inputs.gh_app_key }}
        gh_app_name: ${{ inputs.gh_app_name }}
        project_name: ${{ inputs.project_name }}
    - name: Upload logs
      uses: actions/upload-artifact@v3
      with:
        name: wrangler-logs
        path: wrangler_logs.txt
        retention-days: 3