name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Action'
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run build with Gradle Wrapper
        run: ./gradlew :shadowJar :outputVersion
      - id: dotenv
        uses: falti/dotenv-action@v1
        with:
          path: envs
          export-variables: true
          keys-case: lower

      - name: Checkout v1 release branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "<>"
          git fetch origin
          git symbolic-ref HEAD refs/remotes/origin/release/v1
          git reset
          git add .
          git commit -m "Add release ${{ steps.dotenv.outputs.version }}"
          git push origin HEAD:release/v1

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: v${{ steps.dotenv.outputs.version }}
          message: Publish ${{ steps.dotenv.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: v1
          message: Publish ${{ steps.dotenv.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Image'
        run: |
          docker build . --tag ghcr.io/matyrobbrt/cloudflare-pr-previews:latest --tag ghcr.io/matyrobbrt/cloudflare-pr-previews:${{ steps.dotenv.outputs.version }}
          docker push ghcr.io/matyrobbrt/cloudflare-pr-previews:latest
          docker push ghcr.io/matyrobbrt/cloudflare-pr-previews:${{ steps.dotenv.outputs.version }}