name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Action'
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run build with Gradle Wrapper
        run: ./gradlew :shadowJar :outputVersion
      - name: Set version
        run: APP_VERSION=$(cat version.txt)

      - name: Checkout v1 release branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git fetch origin
          git symbolic-ref HEAD refs/heads/release/v1
          git reset
          git add .
          git commit -m "Add release ${{ env.APP_VERSION }}"
          git push --set-upstream origin release/v1

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ env.APP_VERSION }}
          message: Publish ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: v1
          message: Publish ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Image'
        run: |
          docker build . --tag ghcr.io/matyrobbrt/cloudflare-pr-previews:latest --tag ghcr.io/matyrobbrt/cloudflare-pr-previews:${{ env.APP_VERSION }}
          docker push ghcr.io/matyrobbrt/cloudflare-pr-previews:latest
          docker push ghcr.io/matyrobbrt/cloudflare-pr-previews:${{ env.APP_VERSION }}